### ISSUE TITLE
Crash au lancement du scénario 65 (reproduction des animaux)

### ISSUE THREAD

**Issue by pvincent4** [erasme/museotouch#2]
Kivy 1.9.0

Trigger Exception, traceback info forward to log file.
Traceback (most recent call last):
  File "main.py", line 1350, in <module>
    MuseotouchApp().run()
  File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 824, in run
    runTouchApp()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 539, in mainloop
    self._mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 483, in tick
    self._process_events()
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 615, in _process_events
    event.tick(self._last_tick, remove)
  File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 374, in tick
    ret = callback(self._dt)
  File "main.py", line 501, in update_objects_from_filter
    self.show_objects(items)
  File "main.py", line 241, in show_objects
    x = randint(self.root_images.x + 200, self.root_images.right - 200)
  File "/usr/lib/python2.7/random.py", line 240, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 216, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (200,-198, -398)

**Comment by florian-chassaing** [comment]
Corrigé
