### ISSUE TITLE
Crash au retournement des fiches du scénario 48 (Histoire des arts en mathématiques)

### ISSUE THREAD

**Issue by pvincent4** [erasme/museotouch#3]
Kivy 1.9.0

[INFO   ] [Base        ] Leaving application in progress...
Trigger Exception, traceback info forward to log file.
Traceback (most recent call last):
  File "main.py", line 1350, in <module>
    MuseotouchApp().run()
  File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 824, in run
    runTouchApp()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 487, in runTouchApp
    EventLoop.window.mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 539, in mainloop
    self._mainloop()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
    EventLoop.idle()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 330, in idle
    self.dispatch_input()
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 315, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 221, in post_dispatch_input
    listener.dispatch('on_motion', etype, me)
  File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 904, in on_motion
    self.dispatch('on_touch_down', me)
  File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 920, in on_touch_down
    if w.dispatch('on_touch_down', touch):
  File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
  File "/home/pvincent/Programmation/kivy/educatouch/app/museolib/gesture_board.py", line 36, in on_touch_down
    super(GestureBoard,self).on_touch_down(touch)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 382, in on_touch_down
    if child.dispatch('on_touch_down', touch):
  File "_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:6856)
  File "/home/pvincent/Programmation/kivy/educatouch/app/museolib/widgets/imageitem.py", line 235, in on_touch_down
    ret = super(ImageItem, self).on_touch_down(touch)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/scatter.py", line 531, in on_touch_down
    self._bring_to_front(touch)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/scatter.py", line 492, in _bring_to_front
    parent.remove_widget(self)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/floatlayout.py", line 124, in remove_widget
    return super(FloatLayout, self).remove_widget(widget)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/layout.py", line 87, in remove_widget
    return super(Layout, self).remove_widget(widget)
  File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 509, in remove_widget
    widget.parent = None
  File "properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4543)
  File "properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5025)
  File "properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5641)
  File "_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:11690)
  File "_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11029)
  File "/home/pvincent/Programmation/kivy/educatouch/app/museolib/widgets/imageitem.py", line 408, in on_parent
    self.content.stop()
  File "/home/pvincent/Programmation/kivy/educatouch/app/museolib/widgets/imageitem.py", line 116, in stop
    self.mediacontent.stop()
  File "/home/pvincent/Programmation/kivy/educatouch/app/museolib/widgets/imageitem.py", line 90, in stop
    self.parent.parent.parent.parent.app.media_playing = False
AttributeError: 'NoneType' object has no attribute 'parent'

**Comment by AntoineJ** [comment]
A priori, le bug est corrigé avec mon dernier commit. A confirmer, mais je n'ai pas réussi à reproduire le bug depuis.

Il fallait remplacer passer par self.parent.imageitem.app.media_playing = False pour éviter la chaîne de parents et le risque d'avoir un des parents null.
